name: text-mining
channels:
  - defaults
dependencies:
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.9.13
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - tzdata=2022f
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blis==0.7.9
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - confection==0.0.3
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - idna==3.4
    - importlib-metadata==5.0.0
    - ipykernel==6.17.0
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.17.0
    - jupyter-client==7.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyterlab==3.5.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.16.2
    - langcodes==3.3.0
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - murmurhash==1.0.9
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.3
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - nltk==3.7
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathy==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - preshed==3.0.8
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyzmq==24.0.1
    - regex==2022.10.31
    - requests==2.28.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - send2trash==1.8.0
    - six==1.16.0
    - smart-open==5.2.1
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.2
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - stack-data==0.6.0
    - terminado==0.17.0
    - thinc==8.1.5
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typer==0.4.2
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - zipp==3.10.0
